namespace CSGOSkinAPI.Services
{
    public class ConstDataService
    {
        private static readonly JsonSerializerOptions JsonOptions = new()
        {
            PropertyNameCaseInsensitive = true
        };

        // Blue Gem catalogue: pattern -> weapon -> paint seed -> { playside/backside blue % }. Case
        // Hardened / Heat Treated carry no gem info in the item cert - the blue look is purely the
        // paint seed (weapon-specific). Loaded from blue-gem.json in the constructor.
        private readonly Dictionary<string, Dictionary<string, Dictionary<string, BlueGemPattern>>> _blueGem;

        // Fade catalogue: pattern ("Fade"/"Amber Fade"/"Acid Fade") -> weapon -> percentage per paint
        // seed (index 0..1000). Loaded from fade.json in the constructor.
        private readonly Dictionary<string, Dictionary<string, double[]>> _fade;

        private readonly ConstData _constData;
        private readonly StickerCatalog _stickers;
        private readonly Dictionary<string, string> _skinImages;

        public ConstDataService()
        {
            var jsonString = File.ReadAllText("const.json");
            _constData = JsonSerializer.Deserialize<ConstData>(jsonString, JsonOptions) ?? new ConstData();

            // sticker_id/keychain_id -> {name, image}, generated by scripts/update_skin_data.py.
            // Missing is fine: a brand-new decal the catalog predates resolves to null and the
            // frontend shows a labeled placeholder instead.
            var stickerJson = File.ReadAllText("stickers.json");
            _stickers = JsonSerializer.Deserialize<StickerCatalog>(stickerJson, JsonOptions) ?? new StickerCatalog();

            // "<defindex>_<paintindex>" -> skin image. The decoded item carries no image, so the
            // item page relies on this; keyed by weapon too since a paint kit looks different on
            // each weapon it appears on.
            var skinImageJson = File.ReadAllText("skin-images.json");
            _skinImages = JsonSerializer.Deserialize<Dictionary<string, string>>(skinImageJson, JsonOptions) ?? [];

            // Built by scripts/update_bluegem.js from csfloat/extension's MIT data file (the CSBlueGem
            // numbers). Optional — absence just means Case Hardened / Heat Treated items go unlabelled.
            _blueGem = File.Exists("blue-gem.json")
                ? JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, Dictionary<string, BlueGemPattern>>>>(
                      File.ReadAllText("blue-gem.json"), JsonOptions) ?? []
                : [];

            // Built by scripts/update_fade.js from chescos/csgo-fade-percentage-calculator's MIT
            // generated tables (the rotation-accurate percentages CSFloat & co. use). Optional —
            // absence just means Fade / Amber Fade / Acid Fade items go unlabelled.
            _fade = File.Exists("fade.json")
                ? JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, double[]>>>(
                      File.ReadAllText("fade.json"), JsonOptions) ?? []
                : [];
        }

        public StickerKit? ResolveSticker(uint stickerId) => Resolve(_stickers.Stickers, stickerId);

        public StickerKit? ResolveKeychain(uint keychainId) => Resolve(_stickers.Keychains, keychainId);

        private static StickerKit? Resolve(Dictionary<string, StickerKit>? map, uint id)
            => map != null && map.TryGetValue(id.ToString(), out var kit) ? kit : null;

        // Representative image for a skin, or "" for vanilla/unknown combos (paintindex 0 and
        // anything the catalog predates).
        public string ResolveSkinImage(uint defindex, uint paintindex)
            => _skinImages.TryGetValue($"{defindex}_{paintindex}", out var image) ? image : "";

        public ItemInformation GetItemInformation(CEconItemPreviewDataBlock item)
        {
            // Paint-less items (passes, some medals, ...) reuse this lookup for their
            // display name, but gaps are expected for types the community data doesn't
            // cover and the frontend shows Steam's own name for them anyway. Only a
            // skinned weapon's absence is a signal that const.json needs regenerating.
            var weaponType = GetWeaponName(item.defindex, warnIfMissing: item.paintindex != 0);
            var pattern = GetPatternName(item.paintindex);
            var paintseed = (int)item.paintseed;
            var paintindex = (int)item.paintindex;
            var paintWear = GetPaintWear(item.paintwear);
            var wearName = GetWearFromFloat(paintWear);
            var isKnifeOrGlove = IsKnifeOrGlove(item.defindex);
            var isSouvenir = IsSouvenir(item.quality);

            var special = "";

            if (pattern == "Marble Fade" && _constData.Fireice?.Contains(weaponType) == true
                && paintseed >= 0 && paintseed < _constData.FireiceOrder!.Length)
            {
                var fireiceIndex = _constData.FireiceOrder[paintseed];
                if (fireiceIndex >= 0 && fireiceIndex < ConstData.FireIceNames.Length)
                {
                    special = ConstData.FireIceNames[fireiceIndex];
                }
            }
            // Fade / Amber Fade / Acid Fade all share one per-weapon seed -> % table (fade.json). A
            // paintseed outside 0..1000 comes only from a crafted cert; it falls through unlabelled.
            else if (_fade.TryGetValue(pattern, out var fadeByWeapon)
                && fadeByWeapon.TryGetValue(weaponType, out var fadeTable)
                && paintseed >= 0 && paintseed < fadeTable.Length)
            {
                special = fadeTable[paintseed].ToString("0.#", CultureInfo.InvariantCulture) + "%";
            }
            else if ((pattern == "Doppler" || pattern == "Gamma Doppler") && _constData.Doppler?.ContainsKey(paintindex.ToString()) == true)
            {
                special = _constData.Doppler[paintindex.ToString()];
            }
            else if (pattern == "Crimson Kimono" && _constData.Kimonos?.ContainsKey(paintseed.ToString()) == true)
            {
                special = _constData.Kimonos[paintseed.ToString()];
            }
            else if (_blueGem.TryGetValue(pattern, out var byWeapon)
                && byWeapon.TryGetValue(weaponType, out var gemSeeds)
                && gemSeeds.TryGetValue(paintseed.ToString(), out var gem))
            {
                special = FormatBlueGem(item.defindex, gem);
            }

            return new ItemInformation
            {
                Name = pattern,
                Type = weaponType,
                Special = special,
                WearName = wearName,
                RarityName = GetRarityFromNumber(item.rarity),
                QualityName = GetQualityFromNumber(item.quality),
                OriginName = GetOriginFromNumber(item.origin),
                PaintWear = paintWear,
                IsKnifeOrGlove = isKnifeOrGlove,
                IsSouvenir = isSouvenir,
                MarketHashName = GetMarketHashName(weaponType, pattern, wearName, isKnifeOrGlove, isSouvenir, item.ShouldSerializekilleatervalue())
            };
        }

        private string GetMarketHashName(string weaponType, string pattern, string wearName, bool isKnifeOrGlove, bool isSouvenir, bool isStatTrak)
        {
            var marketHashName = "";
            if (isKnifeOrGlove) marketHashName += GetQualityFromNumber(3) + " "; // ★
            if (isSouvenir) marketHashName += GetQualityFromNumber(12) + " "; // Souvenir
            else if (isStatTrak) marketHashName += GetQualityFromNumber(9) + " "; // StatTrak™

            marketHashName += weaponType;

            if (pattern != GetPatternName(0)) // Vanilla
            {
                marketHashName += $" | {pattern} ({wearName})";
            }
            return marketHashName;
        }

        private string GetWeaponName(uint defIndex, bool warnIfMissing = true)
        {
            if (_constData.Items?.TryGetValue(defIndex.ToString(), out var weapon) == true)
            {
                return weapon;
            }

            if (warnIfMissing)
            {
                Console.WriteLine($"Item {defIndex} is missing from constants");
            }
            return "";
        }

        private string GetPatternName(uint paintIndex)
        {
            if (_constData.Skins?.TryGetValue(paintIndex.ToString(), out var pattern) == true)
            {
                return pattern;
            }

            Console.WriteLine($"Skin {paintIndex} is missing from constants");
            return "";
        }

        private static double GetPaintWear(uint paintWear)
        {
            return (double)BitConverter.UInt32BitsToSingle(paintWear);
        }

        private static string GetWearFromFloat(double paintWear)
        {
            if (paintWear < 0.07) return "Factory New";
            if (paintWear < 0.15) return "Minimal Wear";
            if (paintWear < 0.38) return "Field-Tested";
            if (paintWear < 0.45) return "Well-Worn";
            return "Battle-Scarred";
        }

        private string GetRarityFromNumber(uint rarity)
        {
            if (_constData.Rarities != null && rarity < _constData.Rarities.Count)
            {
                return _constData.Rarities[(int)rarity];
            }
            return "Unknown";
        }

        private string GetOriginFromNumber(uint origin)
        {
             if (_constData.Origins?.TryGetValue(origin.ToString(), out var originName) == true)
             {
                 return originName;
             }
             return "Unknown";
        }

        private static bool IsSouvenir(uint quality)
        {
            return quality == 12;
        }

        private string GetQualityFromNumber(uint quality)
        {
             if (_constData.Qualities?.TryGetValue(quality.ToString(), out var qualityName) == true)
             {
                 return qualityName;
             }
             return "Unknown";
        }

        // Blue-gem label for a Case Hardened / Heat Treated item. Collectors judge knives on the
        // playside. The AK-47 (defindex 7) is special: its two faces are the "top" (playside) and the
        // "magazine" (backside), and a blue magazine is independently prized — so it can surface both.
        private static string FormatBlueGem(uint defindex, BlueGemPattern gem)
        {
            static int Pct(double v) => (int)Math.Round(v);
            var mag = gem.Bb ?? 0;

            if (defindex == 7) // AK-47: top / magazine
            {
                if (gem.Pb >= 38.4)
                {
                    return mag > 30
                        ? $"Blue Gem {Pct(gem.Pb)}% / {Pct(mag)}% mag"
                        : $"Blue Gem {Pct(gem.Pb)}%";
                }
                return mag > 30 ? $"Blue Gem {Pct(mag)}% mag" : "";
            }

            // Knives + other guns: judged on the playside.
            return gem.Pb >= 30 ? $"Blue Gem {Pct(gem.Pb)}%" : "";
        }

        private static bool IsKnifeOrGlove(uint defindex)
        {
            // Knives typically have defindex 500-600
            // Gloves typically have defindex 5000+
            return (defindex >= 500 && defindex < 600) || defindex >= 5000;
        }
    }

    // One blue-gem pattern from blue-gem.json (harvested by scripts/update_bluegem.js from
    // csfloat/extension, MIT). Pb/Bb = playside/backside blue % (raw).
    public class BlueGemPattern
    {
        public double Pb { get; set; }  // playside blue % (raw)
        public double? Bb { get; set; } // backside blue % (raw)
    }
}
