// Data models: Steam web-API inventory/profile shapes, the generated const.json/
// stickers.json catalogs, and the decoded-item view model.
namespace CSGOSkinAPI.Models
{
    public class SteamAccount
    {
        [JsonPropertyName("username")]
        public string Username { get; set; } = string.Empty;

        [JsonPropertyName("password")]
        public string Password { get; set; } = string.Empty;
    }

    public class ItemInformation
    {
        public string Name { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
        public string Special { get; set; } = string.Empty;
        public string WearName { get; set; } = string.Empty;
        public string RarityName { get; set; } = string.Empty;
        public string QualityName { get; set; } = string.Empty;
        public string OriginName { get; set; } = string.Empty;
        public double PaintWear { get; set; }
        public bool IsKnifeOrGlove { get; set; }
        public bool IsSouvenir { get; set; }
        public string MarketHashName { get; set; } = string.Empty;
    }

    public class ConstData
    {
        public Dictionary<string, string>? Items { get; set; }
        public Dictionary<string, string>? Skins { get; set; }
        public Dictionary<string, bool>? Fades { get; set; }
        public Dictionary<string, bool>? AmberFades { get; set; }
        [JsonPropertyName("fade_order")]
        public int[]? FadeOrder { get; set; }
        public string[]? Fireice { get; set; }
        [JsonPropertyName("fireice_order")]
        public int[]? FireiceOrder { get; set; }
        public Dictionary<string, string>? Doppler { get; set; }
        public Dictionary<string, string>? Kimonos { get; set; }
        public List<string>? Rarities { get; set; }
        public Dictionary<string, string>? Qualities { get; set; }
        public Dictionary<string, string>? Origins { get; set; }

        public static readonly string[] FireIceNames = ["", "1st Max", "2nd Max", "3rd Max", "4th Max", "5th Max", "6th Max", "7th Max", "8th Max", "9th Max", "10th Max", "FFI"];
    }

    // stickers.json: two id -> {name, image} maps the server uses to resolve applied
    // stickers and charms. Generated by scripts/update_skin_data.py from the game files.
    public class StickerCatalog
    {
        public Dictionary<string, StickerKit>? Stickers { get; set; }
        public Dictionary<string, StickerKit>? Keychains { get; set; }
    }

    public class StickerKit
    {
        public string Name { get; set; } = string.Empty;
        public string Image { get; set; } = string.Empty;
    }

    public class SteamInventoryResponse
    {
        [JsonPropertyName("assets")]
        public List<SteamAsset>? assets { get; set; }
        
        [JsonPropertyName("descriptions")]
        public List<SteamDescription>? descriptions { get; set; }
        
        [JsonPropertyName("asset_properties")]
        public List<SteamAssetProperties>? asset_properties { get; set; }

        [JsonPropertyName("total_inventory_count")]
        public int total { get; set; }

        [JsonPropertyName("success")]
        public int success { get; set; }
    }

    // Per-asset properties; see GetInventoryData for how %propid:N% inspect-link
    // placeholders resolve against these. Steam sends every value as a string under
    // int_value/float_value/string_value depending on the property's type.
    public class SteamAssetProperties
    {
        [JsonPropertyName("assetid")]
        public string assetid { get; set; } = string.Empty;

        [JsonPropertyName("asset_properties")]
        public List<SteamAssetProperty>? asset_properties { get; set; }
    }

    public class SteamAssetProperty
    {
        [JsonPropertyName("propertyid")]
        public int propertyid { get; set; }

        [JsonPropertyName("int_value")]
        public string? int_value { get; set; }

        [JsonPropertyName("float_value")]
        public string? float_value { get; set; }

        [JsonPropertyName("string_value")]
        public string? string_value { get; set; }
    }

    public class SteamAsset
    {
        [JsonPropertyName("appid")]
        public int appid { get; set; }
        
        [JsonPropertyName("contextid")]
        public string? contextid { get; set; }
        
        [JsonPropertyName("assetid")]
        public string assetid { get; set; } = string.Empty;
        
        [JsonPropertyName("classid")]
        public string classid { get; set; } = string.Empty;
        
        [JsonPropertyName("instanceid")]
        public string instanceid { get; set; } = string.Empty;
        
        [JsonPropertyName("amount")]
        public string? amount { get; set; }
    }

    public class SteamDescription
    {
        [JsonPropertyName("appid")]
        public int appid { get; set; }
        
        [JsonPropertyName("classid")]
        public string classid { get; set; } = string.Empty;
        
        [JsonPropertyName("instanceid")]
        public string instanceid { get; set; } = string.Empty;
        
        [JsonPropertyName("name")]
        public string? name { get; set; }
        
        [JsonPropertyName("market_name")]
        public string? market_name { get; set; }
        
        [JsonPropertyName("market_hash_name")]
        public string? market_hash_name { get; set; }
        
        [JsonPropertyName("name_color")]
        public string? name_color { get; set; }
        
        [JsonPropertyName("background_color")]
        public string? background_color { get; set; }
        
        [JsonPropertyName("icon_url")]
        public string? icon_url { get; set; }
        
        [JsonPropertyName("icon_url_large")]
        public string? icon_url_large { get; set; }
        
        [JsonPropertyName("type")]
        public string? type { get; set; }
        
        [JsonPropertyName("tradable")]
        public int tradable { get; set; }
        
        [JsonPropertyName("marketable")]
        public int marketable { get; set; }
        
        [JsonPropertyName("commodity")]
        public int commodity { get; set; }
        
        [JsonPropertyName("market_tradable_restriction")]
        public int market_tradable_restriction { get; set; }
        
        [JsonPropertyName("actions")]
        public List<SteamAction>? actions { get; set; }

        [JsonPropertyName("descriptions")]
        public List<SteamItemDescription>? descriptions { get; set; }

        [JsonPropertyName("tags")]
        public List<SteamTag>? tags { get; set; }
    }

    public class SteamAction
    {
        [JsonPropertyName("link")]
        public string? link { get; set; }
        
        [JsonPropertyName("name")]
        public string? name { get; set; }
    }

    public class SteamItemDescription
    {
        [JsonPropertyName("type")]
        public string? type { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("value")]
        public string? value { get; set; }
    }

    public class SteamTag
    {
        [JsonPropertyName("category")]
        public string? category { get; set; }
        
        [JsonPropertyName("internal_name")]
        public string? internal_name { get; set; }
        
        [JsonPropertyName("localized_category_name")]
        public string? localized_category_name { get; set; }
        
        [JsonPropertyName("localized_tag_name")]
        public string? localized_tag_name { get; set; }
    }
}
